export const MODELS = [
  // OpenAI 系列
  { id: 'gpt-4-turbo', name: 'GPT-4 Turbo' },
  { id: 'gpt-4', name: 'GPT-4' },
  { id: 'gpt-4o', name: 'GPT-4o' },
  { id: 'gpt-4o-mini', name: 'GPT-4o mini' },
  { id: 'gpt-3.5-turbo', name: 'GPT-3.5 Turbo' },
  { id: 'o1-preview', name: 'OpenAI o1 Preview' },
  { id: 'o1-mini', name: 'OpenAI o1 Mini' },
  
  // Claude 系列
  { id: 'claude-3-5-sonnet', name: 'Claude 3.5 Sonnet' },
  { id: 'claude-3-opus', name: 'Claude 3 Opus' },
  { id: 'claude-3-sonnet', name: 'Claude 3 Sonnet' },
  { id: 'claude-3-haiku', name: 'Claude 3 Haiku' },
  { id: 'claude-4-opus', name: 'Claude 4 Opus' },
  { id: 'claude-4-sonnet', name: 'Claude 4 Sonnet' },
  
  // 国内大模型
  { id: 'qwen-max', name: '通义千问 Max' },
  { id: 'qwen-plus', name: '通义千问 Plus' },
  { id: 'qwen-turbo', name: '通义千问 Turbo' },
  { id: 'qwen-long', name: '通义千问 Long' },
  { id: 'qwen-vl-max', name: '通义千问 VL Max' },
  { id: 'qwen-vl-plus', name: '通义千问 VL Plus' },
  { id: 'qwen-audio-turbo', name: '通义千问 Audio Turbo' },
  { id: 'qwen2-72b', name: '通义千问2 72B' },
  { id: 'qwen2-57b', name: '通义千问2 57B' },
  { id: 'qwen2-7b', name: '通义千问2 7B' },
  
  { id: 'deepseek-chat', name: 'DeepSeek Chat' },
  { id: 'deepseek-coder', name: 'DeepSeek Coder' },
  { id: 'deepseek-v3', name: 'DeepSeek V3' },
  { id: 'deepseek-r1', name: 'DeepSeek R1' },
  
  { id: 'moonshot-v1-8k', name: 'Kimi Chat 8K' },
  { id: 'moonshot-v1-32k', name: 'Kimi Chat 32K' },
  { id: 'moonshot-v1-128k', name: 'Kimi Chat 128K' },
  { id: 'moonshot-v2-8k', name: 'Kimi Chat V2 8K' },
  { id: 'moonshot-v2-32k', name: 'Kimi Chat V2 32K' },
  { id: 'moonshot-v2-128k', name: 'Kimi Chat V2 128K' },
  
  { id: 'glm-4', name: '智谱 GLM-4' },
  { id: 'glm-4v', name: '智谱 GLM-4V' },
  { id: 'glm-3-turbo', name: '智谱 GLM-3 Turbo' },
  { id: 'glm-4-air', name: '智谱 GLM-4 Air' },
  { id: 'glm-4-airx', name: '智谱 GLM-4 AirX' },
  { id: 'glm-4-long', name: '智谱 GLM-4 Long' },
  { id: 'glm-4-flash', name: '智谱 GLM-4 Flash' },
  { id: 'glm-4-plus', name: '智谱 GLM-4 Plus' },
  
  { id: 'yi-large', name: '零一万物 Yi Large' },
  { id: 'yi-medium', name: '零一万物 Yi Medium' },
  { id: 'yi-vision', name: '零一万物 Yi Vision' },
  { id: 'yi-large-rag', name: '零一万物 Yi Large RAG' },
  { id: 'yi-large-turbo', name: '零一万物 Yi Large Turbo' },
  { id: 'yi-large-preview', name: '零一万物 Yi Large Preview' },
  
  { id: 'baichuan3-turbo', name: '百川 Baichuan3 Turbo' },
  { id: 'baichuan4', name: '百川 Baichuan4' },
  { id: 'baichuan5-turbo', name: '百川 Baichuan5 Turbo' },
  { id: 'baichuan5-pro', name: '百川 Baichuan5 Pro' },
  
  { id: 'minimax-abab6.5', name: 'Minimax abab6.5' },
  { id: 'minimax-abab6.5s', name: 'Minimax abab6.5s' },
  { id: 'minimax-abab7', name: 'Minimax abab7' },
  { id: 'minimax-abab8s', name: 'Minimax abab8s' },
  
  { id: 'step-1-8k', name: '阶跃星辰 Step 1 8K' },
  { id: 'step-1-32k', name: '阶跃星辰 Step 1 32K' },
  { id: 'step-1-128k', name: '阶跃星辰 Step 1 128K' },
  { id: 'step-1-256k', name: '阶跃星辰 Step 1 256K' },
  { id: 'step-2-16k', name: '阶跃星辰 Step 2 16K' },
  { id: 'step-2-128k', name: '阶跃星辰 Step 2 128K' },
  { id: 'step-2-256k', name: '阶跃星辰 Step 2 256K' },
  { id: 'step-2v-32k', name: '阶跃星辰 Step 2V 32K' },
  { id: 'step-2v-256k', name: '阶跃星辰 Step 2V 256K' },
  
  { id: 'ernie-4.5', name: '文心一言 ERNIE 4.5' },
  { id: 'ernie-4.0', name: '文心一言 ERNIE 4.0' },
  { id: 'ernie-3.5', name: '文心一言 ERNIE 3.5' },
  { id: 'ernie-speed', name: '文心一言 ERNIE Speed' },
  { id: 'ernie-tiny', name: '文心一言 ERNIE Tiny' },
  { id: 'ernie-char-8k', name: '文心一言 ERNIE Char 8K' },
  { id: 'ernie-func-8k', name: '文心一言 ERNIE Func 8K' },
  { id: 'ernie-lite-8k', name: '文心一言 ERNIE Lite 8K' },
  { id: 'ernie-bot-4', name: '文心一言 ERNIE Bot 4' },
  { id: 'ernie-bot-8k', name: '文心一言 ERNIE Bot 8K' },
  { id: 'ernie-longtext', name: '文心一言 ERNIE LongText' },
  { id: 'ernie-novel-8k', name: '文心一言 ERNIE Novel 8K' },
  { id: 'ernie-vilg-v4', name: '文心一言 ERNIE VilG V4' },
  
  // 其他模型
  { id: 'llama-3.1-405b', name: 'Llama 3.1 405B' },
  { id: 'llama-3.1-70b', name: 'Llama 3.1 70B' },
  { id: 'llama-3.1-8b', name: 'Llama 3.1 8B' },
  { id: 'llama-3-70b', name: 'Llama 3 70B' },
  { id: 'llama-3-8b', name: 'Llama 3 8B' },
  { id: 'llama-3.2-90b', name: 'Llama 3.2 90B' },
  { id: 'llama-3.2-11b', name: 'Llama 3.2 11B' },
  { id: 'llama-3.2-3b', name: 'Llama 3.2 3B' },
  { id: 'llama-3.2-1b', name: 'Llama 3.2 1B' },
  { id: 'llama-3.3-70b', name: 'Llama 3.3 70B' },
  { id: 'llama-3.3-8b', name: 'Llama 3.3 8B' },
  
  { id: 'mixtral-8x7b', name: 'Mixtral 8x7B' },
  { id: 'mixtral-8x22b', name: 'Mixtral 8x22B' },
  { id: 'mixtral-8x7b-instruct', name: 'Mixtral 8x7B Instruct' },
  { id: 'mixtral-8x22b-instruct', name: 'Mixtral 8x22B Instruct' },
  
  { id: 'mistral-large', name: 'Mistral Large' },
  { id: 'mistral-medium', name: 'Mistral Medium' },
  { id: 'mistral-small', name: 'Mistral Small' },
  { id: 'mistral-large-2', name: 'Mistral Large 2' },
  { id: 'mistral-small-2', name: 'Mistral Small 2' },
  { id: 'codestral', name: 'Codestral' },
  { id: 'mathstral', name: 'Mathstral' },
  { id: 'mistral-nemo', name: 'Mistral Nemo' },
  { id: 'mistral-large-3', name: 'Mistral Large 3' },
  { id: 'pixtral-12b', name: 'Pixtral 12B' },
  { id: 'pixtral-large', name: 'Pixtral Large' },
  
  { id: 'gemini-pro', name: 'Gemini Pro' },
  { id: 'gemini-pro-vision', name: 'Gemini Pro Vision' },
  { id: 'gemini-1.5-pro', name: 'Gemini 1.5 Pro' },
  { id: 'gemini-1.5-flash', name: 'Gemini 1.5 Flash' },
  { id: 'gemini-2.0-flash', name: 'Gemini 2.0 Flash' },
  { id: 'gemini-2.0-pro', name: 'Gemini 2.0 Pro' },
  { id: 'gemini-1.0-pro', name: 'Gemini 1.0 Pro' },
  { id: 'gemini-1.0-ultra', name: 'Gemini 1.0 Ultra' },
  
  { id: 'midjourney', name: 'Midjourney' },
  { id: 'midjourney-v5', name: 'Midjourney V5' },
  { id: 'midjourney-v6', name: 'Midjourney V6' },
  { id: 'midjourney-niji', name: 'Midjourney Niji' },
];

export const CATEGORIES = [
  'Writing',
  'Programming',
  'Translation',
  'Creativity',
  'Learning',
  'Business',
  'Marketing',
  'Education',
];

export const TAG_COLORS: Record<string, string> = {
  Writing: 'bg-blue-100 text-blue-800',
  Programming: 'bg-green-100 text-green-800',
  Translation: 'bg-purple-100 text-purple-800',
  Creativity: 'bg-pink-100 text-pink-800',
  Learning: 'bg-yellow-100 text-yellow-800',
  Business: 'bg-indigo-100 text-indigo-800',
  Marketing: 'bg-red-100 text-red-800',
  Education: 'bg-teal-100 text-teal-800',
};